services:
  - type: worker
    name: telegram-reviews-bot
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
    rootDir: .

    
  